language: ruby
before_script: cp config/worker.example.yml config/worker.yml
script: rspec spec
bundler_args: --without development debug
rvm:
  - jruby-18mode
  - jruby-19mode
  - jruby-head
env:
  - JRUBY_OPTS="--server -Xcext.enabled=false -Xcompile.invokedynamic=false"
jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7
