queue: builds
shell:
  buffer: 1.5
vms:
  count: 5
  base: lucid32_old
  memory: 1536
  cookbooks: 'vendor/cookbooks/vagrant_base'
  log_level: 'info'
  json:
    rvm:
      rubies:
      - name: rbx-head
        arguments: --branch 2.0.testing
        using: 1.8.7
      - name: rbx-head
        arguments: -n d19 --branch 2.0.testing -- --default-version=1.9
        using: 1.9.3
        check_for: rbx-head-d19
      - name: 1.8.7
      - name: jruby
      - name: ree
      - name: 1.9.2
      - name: 1.9.3
      - name: ruby-head
      - name: 1.8.6
      gems:
        - bundler
        - rake
        - chef
      aliases:
        rbx: rbx-head
        rbx-2.0: rbx-head
        rbx-2.0.0pre: rbx-head
    mysql:
      server_root_password: ""
    postgresql:
      max_connections: 256
    travis_build_environment:
      use_tmpfs_for_builds: false
  recipes:
    - travis_build_environment
    - apt
    - build-essential
    - scons
    - networking_basic
    - openssl
    - sysctl
    - libyaml # libyaml MUST be installed before rubies. MK.
    - emacs::nox
    - vim
    - timetrap
    - git
    - java
    - ant
    - maven
    - leiningen
    - libqt4
    - libgdbm
    - libncurses
    - libossp-uuid
    - libv8
    - ragel
    - nodejs
    - rvm
    - rvm::multi
    - sqlite
    - postgresql::client
    - postgresql::server
    - mysql::client
    - mysql::server
    - redis
    - riak
    - mongodb
    - couchdb
    - memcached
    - rabbitmq::with_management_plugin
    - imagemagick
    - sphinx::all
    - xserver
    - firefox
    - kerl
    - python
    - python::multi
