env: ruby
ruby:
  log_level: info
  amqp:
    host: localhost
    port: 5672
    username: travisci_worker
    password: travisci_worker_password
    virtual_host: travisci.development
  vms:
    count: 1
    vbox_home: '/usr/lib/virtualbox'
